// Generated by nginx-to-edge-js vcrossplane-1.0.0
// Source: unknown
// Generated at: 2025-08-11T15:36:09.902Z
// Target platform: CloudFlareGenerator

addEventListener("fetch", event => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest(request) {
  const url = new URL(request.url);
  const hostname = url.hostname;

  // Server block 1
  if (hostname === "www.example.com" || hostname === "example.com") {
  }

  // Server block 2
  if (hostname === "example.com") {
    // Location: /blog
    if (url.pathname === "/blog" || url.pathname.startsWith("/blog/")) {
      const redirectUrl = "https://blog.example.com$request_uri";
      return Response.redirect(redirectUrl, 301);
    }

    // Location: /api/
    if (url.pathname.startsWith("/api/")) {
      // Proxy to: http://api.example.com/
      return await proxyRequest(request, "http://api.example.com/", url);
    }

    // Location: ~*
    if (url.pathname === "~*" || url.pathname.startsWith("~*/")) {
      // Static file serving - requires CloudFlare Pages or R2
      return new Response("Static file serving not implemented", { status: 501 });
    }

    // Location: /
    if (url.pathname.startsWith("/")) {
      // Static file serving - requires CloudFlare Pages or R2
      return new Response("Static file serving not implemented", { status: 501 });
    }
  }


  // Default response
  return new Response("Not Found", { status: 404 });
}

// Helper function to proxy requests
async function proxyRequest(request, backend, url) {
  const backendUrl = new URL(backend);
  const proxyUrl = new URL(url.pathname + url.search, backendUrl);

  // Copy headers
  const headers = new Headers(request.headers);
  headers.set("Host", backendUrl.hostname);
  headers.set("X-Forwarded-For", request.headers.get("CF-Connecting-IP") || "");
  headers.set("X-Real-IP", request.headers.get("CF-Connecting-IP") || "");

  const response = await fetch(proxyUrl, {
    method: request.method,
    headers: headers,
    body: request.body
  });

  // Copy response headers
  const responseHeaders = new Headers(response.headers);
  
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: responseHeaders
  });
}