// Generated by nginx-to-edge-js v1.0.0
// Source: examples/simple.ucl
// Generated at: 2025-08-07T01:58:27.141Z
// Target platform: NextJSGenerator

import { NextRequest, NextResponse } from "next/server";
import type { NextFetchEvent } from "next/server";

export function middleware(request: NextRequest, event: NextFetchEvent) {
  const url = request.nextUrl.clone();
  const hostname = request.headers.get("host") || "";

  // Server block 1
  if (hostname === "example.com") {
  }


  // Continue to next middleware or page
  return NextResponse.next();
}

export const config = {
  matcher: [
    
  ]
};