// Generated by nginx-to-edge-js vcrossplane-1.0.0
// Source: unknown
// Generated at: 2025-08-11T15:32:41.552Z
// Target platform: NextJSGenerator

import { NextRequest, NextResponse } from "next/server";
import type { NextFetchEvent } from "next/server";

export function middleware(request: NextRequest, event: NextFetchEvent) {
  const url = request.nextUrl.clone();
  const hostname = request.headers.get("host") || "";

  // Server block 1
  if (hostname === "example.com") {
    // Location: /static/
    if (url.pathname.startsWith("/static/")) {
      // Static files served from /public directory
      return NextResponse.next();
    }

    // Location: /api/
    if (url.pathname.startsWith("/api/")) {
      // Proxy to: http://backend:3000/
      const backendUrl = new URL("http://backend:3000/");
      backendUrl.pathname = url.pathname;
      backendUrl.search = url.search;
      return NextResponse.rewrite(backendUrl);
    }

    // Location: /
    if (url.pathname.startsWith("/")) {
      url.pathname = "https://$server_name$request_uri";
      return NextResponse.redirect(url, 301);
    }
  }


  // Continue to next middleware or page
  return NextResponse.next();
}

export const config = {
  matcher: [
    "/api/:path*",
    "/static/:path*",
    "/"
  ]
};