// Generated by nginx-to-edge-js vcrossplane-1.0.0
// Source: unknown
// Generated at: 2025-08-11T19:38:27.793Z
// Target platform: NextJSGenerator

import { NextRequest, NextResponse } from "next/server";
import type { NextFetchEvent } from "next/server";

export function middleware(request: NextRequest, event: NextFetchEvent) {
  const url = request.nextUrl.clone();
  const hostname = request.headers.get("host") || "";

  // Server block 1
  if (hostname === "example.com") {
    // Location: /
    if (url.pathname.startsWith("/")) {
      // Proxy to: http://backend:3000
      const backendUrl = new URL("http://backend:3000");
      backendUrl.pathname = url.pathname;
      backendUrl.search = url.search;
      return NextResponse.rewrite(backendUrl);
    }
  }


  // Continue to next middleware or page
  return NextResponse.next();
}

export const config = {
  matcher: [
    "/"
  ]
};