name: CI - RHEL

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package*.json'
      - 'tsconfig.json'
      - 'jest.config.cjs'
      - 'eslint.config.js'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'package*.json'
      - 'tsconfig.json'
      - 'jest.config.cjs'
      - 'eslint.config.js'
      - '.github/workflows/**'

jobs:
  test-rhel:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    
    steps:
    - name: Install Git and basic tools
      run: |
        dnf update -y
        dnf install -y --allowerasing git curl python3 python3-pip

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install crossplane
      run: |
        pip3 install crossplane

    - name: Verify crossplane installation
      run: |
        crossplane --version
        echo "crossplane installed successfully on RHEL"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Test CLI functionality
      run: |
        echo "=== Testing Simplified CLI on RHEL ==="
        node dist/src/cli/index.js --help
        echo "=== Testing system dependencies ==="
        node dist/src/cli/index.js check
        echo "=== Testing crossplane integration ==="
        node dist/src/cli/index.js test
        echo "=== Testing nginx parsing ==="
        node dist/src/cli/index.js parse examples/basic-reverse-proxy/nginx.conf
        echo "=== Testing nginx validation ==="
        node dist/src/cli/index.js validate examples/basic-reverse-proxy/nginx.conf
        echo "=== Testing CloudFlare Workers generation ==="
        node dist/src/cli/index.js generate cloudflare examples/basic-reverse-proxy/nginx.conf --output test-worker.js
        echo "=== Testing Next.js middleware generation ==="
        node dist/src/cli/index.js generate nextjs examples/basic-reverse-proxy/nginx.conf --output test-middleware.ts
        echo "=== Testing all platforms generation ==="
        node dist/src/cli/index.js generate all examples/basic-reverse-proxy/nginx.conf --output-dir test-output
        echo "=== Verifying generated files ==="
        ls -la test-worker.js test-middleware.ts test-output/
        echo "=== Testing npm link ==="
        npm link
        echo "=== Testing global CLI ==="
        nginx-to-edge-js --help || echo "CLI not found in PATH"

  release-rhel:
    needs: test-rhel
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Install Git and basic tools
      run: |
        dnf update -y
        dnf install -y --allowerasing git curl python3 python3-pip

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install crossplane
      run: |
        pip3 install crossplane
    
