name: CI - Ubuntu

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install crossplane
      run: |
        pip install crossplane

    - name: Verify crossplane installation
      run: |
        crossplane --version
        echo "crossplane installed successfully"
          pipx install crossplane
          echo "crossplane installed via pipx"
        else
          # Fallback to pip3 with user install
          pip3 install --user crossplane
          echo "crossplane installed via pip3 --user"
          # Add user bin to PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        fi

    - name: Verify libucl installation
      run: |
        # Check for FreeBSD libucl installation
        find /usr/local -name "libucl.so*" 2>/dev/null | head -5
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Test CLI functionality
      run: |
        echo "=== Testing Simplified CLI on Ubuntu ==="
        node dist/src/cli/index.js --help
        echo "=== Testing system dependencies ==="
        node dist/src/cli/index.js check
        echo "=== Testing crossplane integration ==="
        node dist/src/cli/index.js test
        echo "=== Testing nginx parsing ==="
        node dist/src/cli/index.js parse examples/basic-reverse-proxy/nginx.conf
        echo "=== Testing nginx validation ==="
        node dist/src/cli/index.js validate examples/basic-reverse-proxy/nginx.conf
        echo "=== Testing CloudFlare Workers generation ==="
        node dist/src/cli/index.js generate cloudflare examples/basic-reverse-proxy/nginx.conf --output test-worker.js
        echo "=== Testing Next.js middleware generation ==="
        node dist/src/cli/index.js generate nextjs examples/basic-reverse-proxy/nginx.conf --output test-middleware.ts
        echo "=== Testing all platforms generation ==="
        node dist/src/cli/index.js generate all examples/basic-reverse-proxy/nginx.conf --output-dir test-output
        echo "=== Verifying generated files ==="
        ls -la test-worker.js test-middleware.ts test-output/
        echo "=== Testing npm link ==="
        npm link
        echo "=== Testing global CLI ==="
        nginx-to-edge-js --help || echo "CLI not found in PATH"

  release-ubuntu:
    needs: test-ubuntu
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install crossplane
      run: |
        pip install crossplane
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    # Note: Publishing step would be the same as macOS workflow
    # Uncomment when ready to publish to npm
    # - name: Publish to npm
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
