name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install libucl
      run: |
        brew install libucl

    - name: Install crossplane
      run: |
        brew install pipx
        pipx install crossplane

    - name: Verify libucl installation
      run: |
        ls -la /opt/homebrew/Cellar/libucl/*/lib/libucl.dylib
        echo "libucl FFI integration - no ucl_tool binary needed"
    
    - name: Verify crossplane installation
      run: |
        pipx list | grep crossplane || echo "crossplane not found in pipx"
        crossplane --version
        echo "crossplane installed successfully"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Test CLI functionality
      run: |
        echo "=== Testing Unified CLI ==="
        node dist/src/cli/index.js --help
        echo "=== Testing UCL parsing with FFI ==="
        node dist/src/cli/index.js parse examples/simple.ucl
        echo "=== Testing system dependencies ==="
        node dist/src/cli/index.js check
        echo "=== Testing nginx-to-UCL conversion ==="
        node dist/src/cli/index.js preview examples/basic-reverse-proxy/nginx.conf
        echo "=== Testing system integration ==="
        node dist/src/cli/index.js test
        echo "=== Testing npm link ==="
        npm link
        echo "=== Testing global CLI ==="
        nginx-to-edge-js --help || echo "CLI not found in PATH"

  release:
    needs: test
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install libucl
      run: |
        brew install libucl

    - name: Install crossplane
      run: |
        brew install pipx
        pipx install crossplane
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    # Uncomment when ready to publish to npm
    # - name: Publish to npm
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
