name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install libucl (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libucl-dev ucl-utils
    
    - name: Install libucl (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install libucl
    
    - name: Verify libucl installation
      run: |
        which ucl_tool || echo "ucl_tool not found in PATH"
        ucl_tool -h || echo "ucl_tool help failed"
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
      continue-on-error: true
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Test CLI functionality
      run: |
        npm link
        nginx-to-edge-js --help
        nginx-to-edge-js validate examples/basic-reverse-proxy/nginx.conf || echo "CLI validation test completed"

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install libucl
      run: |
        sudo apt-get update
        sudo apt-get install -y libucl-dev ucl-utils
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    # Uncomment when ready to publish to npm
    # - name: Publish to npm
    #   run: npm publish
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
